[project]
name = "vienna-fountains"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jloim", email = "joloimer@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
vienna-fountains = "vienna_fountains:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
